"""'initial_db'

Revision ID: 477bc2d51fd9
Revises: 
Create Date: 2021-10-27 23:01:43.502582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477bc2d51fd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
